[project]
name = "spam"
version = "0.1.0"
description = ""
authors = [{ name = "holzmaster", email = "holzmaster@outlook.com" }]
requires-python = "~=3.12"
readme = "README.md"
dependencies = ["redis>=5.2.1,<6"]

[tool.uv]
package = false
