/** See also $vote-delay in scss */
export const VOTE_DELAY = 200; // 250;
export const VOTE_PRESENT_DELAY = 250;

export const DEV = import.meta.env.DEV;
export const API_BASE = "/api";

/* TODO: Add more sample texts */
export const TEXT_PLACEHOLDERS = [
	"Ich suche Jemanden zum gemeinsamen Posten von Brot. Willst du mit mir Brot posten?",
	"Ich will mit CSGO anfangen, weiß aber nicht, wie es geht.\nKannst du mir helfen?",
	"Ich bin allein und brauche Gesellschaft im disc0rd.",
	"Willst du mir mir gehen? Ich wiege auch nicht so viel",
	"Ich mag richtig dicke Stahlöfen",
	"Nächste Woche will ich ein Pferd stehlen.\nMagst du mir helfen?",
	"Habe einen Minecreaft-Server und suche Griefer.\nWillst du mein Griefer sein?",
	"Komm mal her!",
	"Suche jemanden mit einem 3D-Drucker. Ich würde gerne einen HDMI-auf-Gardena-Adapter drucken.\nIst wichtig!",
	"Kannst du mir erklären, wie man e^x integriert?",
	"Wollen wir zusammen Anime schauen?\nHabe disc0rd und TeamSpeak.",
	"Hi!\nEnde diesen Jahres will ich die Hagia Sophia besuchen und suche noch Mitreisende.",
	'Ich dachte mal, ich versuche es über dieses "Internet". Das wirkt alles noch sehr merkwürdig hier.\nKannst du mir helfen, dass ich mich zurecht finde?',
] as const;

/* TODO: Add more sample tags */
export const TAG_PLACEHOLDERS = [
	"Züge erregen mich",
	"Schiffe erregen mich",
	"richtig fette derbe brachiale ultramelonen",
	"sie klauen unsere jobs",
	"gedämpfte Huscheln",
	"bunte Haare = verrückt",
	"akuter eindringdrang",
	"nsfw",
	"b100",
	"for shure",
	"CSGO",
	"1 Typ",
	"discord",
	"epoche der Geisteskranken",
	"anatomisch komisch",
	"keine Ahnung",
	"lieblingsnachbar",
	"hassfick",
	"kadsen",
	"kadse",
	"feinkostgewölbe",
	"Mathematik der Hurensohn",
	"Esskultur im Mittelalter",
	"Kindheitserinnerung",
	"TeamSpeak",
	"endlaser",
	"hauttyp 1 genau meins",
	"originaler Nichtskönner",
	"danke roter Pfeil",
	"Schmusekadser",
	"Doktortitel in Gönnung",
	"endlich mit Profis",
	"Ostblockromantik",
	"geht auf meine uni",
	"geht auf meinen friedhof",
	"1000 monde",
	"1000 sonnen",
	"name ist pr0gramm",
	"80kg Stahlofen",
	"risikofreudiger Match",
	"ctang der soßenlose",
	"zeig Zitze",
	"links > rechts",
	"links < rechts",
	"( . Y . )?",
	"drachenlord",
	"sportlicher als ich",
	"buttergolem",
	"Regelungstechnik regelt",
	"taktischer Regenschirm",
	"dafür bin ich hier",
	"Ende lohnt",
	"achtung scheiße",
	"achtung richtig scheiße",
	"sfc",
	"ling ling macht schling schling",
	"stift = selbst gemalt",
	"das pr0 bei nacht",
	"das pr0 bei nacht am tag",
	"Gemeiner Spitztitterich",
	"freuvieh",
	"dreitagebart",
	"f man weiß ja nie",
	"Kriegshammer Vierzigtausend",
	"geil weil jung",
	"geil weil geil",
	"3.44% effektiver Jahreszins",
	"Bausparkadse",
	"Mama ist die beste",
	"gute nudel",
	"mlem",
	"kriminell",
	"dezentes Schamhaar",
	"geile Sohlen",
	"danke Mama",
	"hübscher als ich",
	"erderotik",
] as const;
