name: CD-new

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "new/**"

jobs:
  build:
    strategy:
      matrix:
        component: ['frontend', 'backend']

    name: Build Container Images
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/holzmaster/kt-${{ matrix.component }}-2
          tags: |
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          # ${{ github.event_name != 'pull_request' }}
          push: false
          context: ./new/${{ matrix.component }}
          build-contexts: shared=./new/shared
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: linux/amd64
          cache-from: type=gha
          cache-to: type=gha,mode=max
