name: CI-new

on:
  push:
    paths:
      - "new/**"

jobs:
  build:
    strategy:
      matrix:
        component: ['frontend', 'backend']

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - uses: actions/cache@v4
      env:
        cache-name: cache-node-modules
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-${{ matrix.component }}-build-${{ env.cache-name }}-${{ hashFiles('**/bun.lockb') }}

    - name: Build and Test
      working-directory: new/${{ matrix.component }}
      run: |
        bun install
        bun run ci
        bun run test
      env:
        CI: true
